title: ML Optimization (Grad)
author: OptimAI-Lab
copyright: "2025"
logo: ""
# html:
#   toc:
#     sidebar:
#       depth: 2
bibtex_bibfiles:
  - references.bib
execute:
  execute_notebooks: "off" # ["off", "auto"]
math:
   equation_numbering: by_section
sphinx:
  extra_extensions:
    - sphinx_multitoc_numbering
  config:
    proof_theorem_types:
      - theorem
      - lemma
      - proposition
      - corollary
      - definition
      - example
      - remark
      - property
      - algorithm
      - assumption
      - exercise
    proof_title_template: "{name} {number} ({title})"
    copyright: "2025"
    numfig: true                 # Number figures, tables, equations
    html_theme: sphinx_book_theme
    html_theme_options:
      use_numbered_headings: true
      numbered_headings_depth: 3       # 1=H1, 2=H1–H2, 3=H1–H3
      # Make the LEFT SIDEBAR show those same levels (and their numbers)
      show_nav_level: 3                # pydata-sphinx-theme option
    bibtex_reference_style: author_year  # or label
    mathjax3_config:
      tex:
        macros:
          RR: "\\mathbb{R}"
          EE: "\\mathbb{E}"
          CC: "\\mathbb{C}"
          ZZ: "\\mathbb{Z}"
          Var: "\\mathrm{Var}"
          sign: "\\mathrm{sign}"
          argmin: "\\mathrm{argmin}"
          KL: ["\\mathrm{KL}\\left(#1 \\middle\\| #2\\right)", 2]
          vA: "\\mathbf{A}"
          vB: "\\mathbf{B}"
          vC: "\\mathbf{C}"
          vD: "\\mathbf{D}" 
          vE: "\\mathbf{E}"
          vF: "\\mathbf{F}"
          vG: "\\mathbf{G}"
          vH: "\\mathbf{H}"     
          vI: "\\mathbf{I}"
          vJ: "\\mathbf{J}"
          vK: "\\mathbf{K}"
          vL: "\\mathbf{L}"
          vM: "\\mathbf{M}"
          vN: "\\mathbf{N}"
          vO: "\\mathbf{O}"
          vP: "\\mathbf{P}"
          vQ: "\\mathbf{Q}"
          vR: "\\mathbf{R}"
          vS: "\\mathbf{S}"
          vT: "\\mathbf{T}"
          vU: "\\mathbf{U}"
          vV: "\\mathbf{V}"
          vW: "\\mathbf{W}"
          vX: "\\mathbf{X}"
          vY: "\\mathbf{Y}"
          vZ: "\\mathbf{Z}"
          va: "\\mathbf{a}"
          vb: "\\mathbf{b}"
          vc: "\\mathbf{c}"
          vd: "\\mathbf{d}"
          ve: "\\mathbf{e}"
          vf: "\\mathbf{f}"
          vg: "\\mathbf{g}"
          vh: "\\mathbf{h}"
          vi: "\\mathbf{i}"
          vj: "\\mathbf{j}"
          vk: "\\mathbf{k}"
          vl: "\\mathbf{l}"
          vm: "\\mathbf{m}"
          vn: "\\mathbf{n}"
          vo: "\\mathbf{o}"
          vp: "\\mathbf{p}"
          vq: "\\mathbf{q}"
          vr: "\\mathbf{r}"
          vs: "\\mathbf{s}"
          vt: "\\mathbf{t}"
          vu: "\\mathbf{u}"
          vv: "\\mathbf{v}"
          vw: "\\mathbf{w}"
          vx: "\\mathbf{x}"
          vy: "\\mathbf{y}"
          vz: "\\mathbf{z}"
          vnull: "\\mathbf{\\emptyset}"     
          sign: "\\mathrm{sign}"
          SS: "\\mathbb{S}"
          SSp: "\\mathbb{S}_{+}"
          SSpp: "\\mathbb{S}_{++}"
          vzero: "\\mathbf{0}"
          vone: "\\mathbf{1}"
          v0: "\\mathbf{0}"
          v1: "\\mathbf{1}"
          valpha: "\\boldsymbol{\\alpha}"
          vAlpha: "\\boldsymbol{\\Alpha}"
          vbeta: "\\boldsymbol{\\beta}"
          vBeta: "\\boldsymbol{\\Beta}"
          vgamma: "\\boldsymbol{\\gamma}"
          vGamma: "\\boldsymbol{\\Gamma}"
          vdelta: "\\boldsymbol{\\delta}"
          vDelta: "\\boldsymbol{\\Delta}"
          vepsilon: "\\boldsymbol{\\epsilon}"
          vtheta: "\\boldsymbol{\\theta}"
          vphi: "\\boldsymbol{\\phi}"
          vpsi: "\\boldsymbol{\\psi}"
          vomega: "\\boldsymbol{\\omega}"
          vmu: "\\boldsymbol{\\mu}"
          vsigma: "\\boldsymbol{\\sigma}"
          vSigma: "\\boldsymbol{\\Sigma}"
          vLambda: "\\boldsymbol{\\Lambda}"
          vGamma: "\\boldsymbol{\\Gamma}"
          vTheta: "\\boldsymbol{\\Theta}"
          vPhi: "\\boldsymbol{\\Phi}"
          vPsi: "\\boldsymbol{\\Psi}"
          vOmega: "\\boldsymbol{\\Omega}"
          vxi: "\\boldsymbol{\\xi}"
          vXi: "\\boldsymbol{\\Xi}"
          vzeta: "\\boldsymbol{\\zeta}"
          veta: "\\boldsymbol{\\eta}"
          vupsilon: "\\boldsymbol{\\upsilon}"
          vTau: "\\boldsymbol{\\Tau}"
          Proj: "\\mathrm{Proj}"

